### ISSUE TITLE
Can't get it to work with default keyring

### ISSUE THREAD

**Issue by ponderstibbons** [swick/moz-gnome-keyring-integration#10]
If I set the 'extensions.gnome-keyring.keyringName' property in the config to a existing keyring not created by this plugin (in this case named "Default keyring" and also set to be the default per seahorse) the plugin  won't open it correctly, but instead try to create a new keyring with the same name. After it created them however, it seems to think that creating and unlocking failed as it tries to create another keyring with the same name again and again. This way I end up with a couple of keyrings with the same name (all confirmed to exist and be unlocked by seahorse), but the plugin won't use them and will create new ones if I, e.g. try to save a password.

I run Thunderbird 31.2.0 with version 0.5 of your plugin.

**Comment by swick** [comment]
It turns out that whitespaces are replaced by underscore for gnome keyring names. As a woraround you can just use "Default_keyring". There also are problems with non-ascii characters in keyring names.

**Comment by ponderstibbons** [comment]
Thanks for that, I'll try it.
Is fixing this as easy as substituting underscores for whitespace (and other escaping) when reading the value from the config? If so, I can look into this over the weekend.

**Comment by swick** [comment]
Not sure what other rules there are and I'd rather depend on those specifics. It probably makes more sense to implement a settings dialogue where you can choose from the available keyrings.

**Comment by swick** [comment]
fixed in e057802e07f5488db37864d5a178d13927742e03
