### ISSUE TITLE
User/Password List in Settings does not show all passwords

### ISSUE THREAD

**Issue by AndreasA** [swick/moz-gnome-keyring-integration#14]
I think this problem has actually been added after a recent commit

**Comment by AndreasA** [comment]
The issue seems to have been introduced with this commit:
https://github.com/swick/moz-gnome-keyring-integration/commit/5bf9d2bfd42319836442f3e421a04f2846e42c66

**Comment by simontunnat** [comment]
Fixed the bug (see my commit).

**Comment by AndreasA** [comment]
Does work bug I cannot delete passwords with that version?

**Comment by simontunnat** [comment]
I can confirm that my first commit introduced this bug. That didn't change with my second commit.

I will fix this and will try to not introduce more bugs this time.

**Comment by simontunnat** [comment]
See 5f67b1ef5addd16ef0da109f609949be92c2cb42

**Comment by swick** [comment]
Fixed in 27d64093adffeeb5d4cd8acf8a5ae428a9ad989a
