### ISSUE TITLE
Initialize (v32) is different from Init (v31)

### ISSUE THREAD

**Issue by infinity0** [swick/moz-gnome-keyring-integration#7]
Hi, the new `Initialize` method is not the same as `Init`. The former should be asynchronous, returning a Promise, and the latter is synchronous. In `nsILoginManagerStorage.idl`:

~~~~
    /**
     * Initialize the component.
     *
     * At present, other methods of this interface may be called before the
     * returned promise is resolved or rejected.
     *
     * @return {Promise}
     * @resolves When initialization is complete.
     * @rejects JavaScript exception.
     */
    jsval initialize();
~~~~

**Comment by swick** [comment]
Fixed in 27d64093adffeeb5d4cd8acf8a5ae428a9ad989a
we're not doing any synchronous work so it should be okay to just return an empty promise
